### ISSUE TITLE
Performance Benchmarking and Identification of bottlenecks

### ISSUE THREAD

**Issue by smivij** [awslabs/aws-sdk-swift#1038]
Before we GA the SDK we need to benchmark our performance and also improve it where it falls short of the desired performance levels. We need to identify the usage patterns for platforms, services, operations and prioritize accordingly.

------
```[tasklist]
### Tasks
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1520
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1521
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1522
- [ ] Setup an OpenTelemetry Collector that runs in a docker container on ECS to emit metrics to cloudwatch
- [ ] TBD Setup Automation of the executable
- [x] Create a dashbaord to display cloudwatch results
```

Added by @dayaffe 5/21/24

**Comment by sichanyoo** [comment]
There does not exist a cross-SDK standard for accepted benchmarking levels, because it's heavily dependent on the language. Some services to have SLA (e.g., S3Express has SLA for time it takes for operations). 

To gauge which part of the SDK to benchmark, take a look at what other SDKs have done.

Also, consider making list of candidates that may take bulk of the time during request/response flow (e.g., signing for request).

Build a reusable benchmarking tool (if needed) on top of SRA observability and use that.

**Comment by sichanyoo** [comment]
Found a list of recommended metrics for benchmarking: 
/BbKeALtIAOEA/Observability-Tracing-Revised#temp:C:LfW8da6814a06f242928dea883e8

**Comment by dayaffe** [comment]
```[tasklist]
### Tasks
- [ ] Design doc for how Swift SDK will measure performance
- [ ] Implement open-telemetry's swift integration (metrics)
- [ ] Create a swift executable that runs the top X operations and outputs metrics to cloud watch
- [ ] Setup a dashboard that tracks performance over time
- [ ] (Stretch) Run the swift executable as part of github actions across multiple platforms
- [ ] (Stretch) Setup a merge blocker on PRs that introduce performance degredation
```

**Comment by dayaffe** [comment]
See `/RunBooks/PerformanceMetrics/`
