### ISSUE TITLE
Implementation of Flexible Checksums

### ISSUE THREAD

**Issue by dayaffe** [awslabs/aws-sdk-swift#1281]
```[tasklist]
### Tasks
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1287
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1319
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1306
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1328
```

**Comment by jbelkins** [comment]
Closing as Done.
