### ISSUE TITLE
Add support for flexible checksums on Normal payloads

### ISSUE THREAD

**Issue by dayaffe** [awslabs/aws-sdk-swift#1287]
```[tasklist]
### Tasks
- [x] Add a wrapper for CRT provided hash functions
- [x] Add support for httpChecksum trait
- [x] Create a middleware that modifies request to include checksum hash in header
- [x] Create a middleware that validates checksum in response
- [x] Add tests for Normal payload
```

**Comment by sichanyoo** [comment]
Released with: 
https://github.com/awslabs/aws-sdk-swift/releases/tag/0.35.0
https://github.com/smithy-lang/smithy-swift/releases/tag/0.40.0
