### ISSUE TITLE
CRT Modularization

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1512]
### Describe the feature

To provide CRT functionality in small, focused, independent modules.

### Use Case

To complement the modularization of the AWS SDK for Swift.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change
```[tasklist]
### Tasks
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1389
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1390
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1391
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1392
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1393
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1394
```

**Comment by jbelkins** [comment]
Outside the scope of this project, closing.
