### ISSUE TITLE
Implement aws region detection provider chain

### ISSUE THREAD

**Issue by kneekey23** [awslabs/aws-sdk-swift#317]
Define region detection (provider) chain, implement, and integration into: [regionDetection](https://github.com/awslabs/aws-sdk-swift/pull/313/files#diff-c8785d7c993232671b4a04a178eb41135feb3d25f5f9879b36818a0f60be4d60R12)

Depends on:
- [x] awslabs/aws-sdk-swift#173- add region resolver & environment based detection
- [x] awslabs/aws-sdk-swift#318 - system property based detection (info.plist)
- [x] awslabs/aws-sdk-swift#319 - profile based detection
- [x] awslabs/aws-sdk-swift#320 - ec2 metadata based detection

**Comment by wooj2** [comment]
All issues are done, closing.
