### ISSUE TITLE
endpoints 2.0

### ISSUE THREAD

**Issue by ganeshnj** [awslabs/aws-sdk-swift#624]
## Issues

Fixes https://github.com/awslabs/aws-sdk-swift/issues/533
Fixes https://github.com/awslabs/aws-sdk-swift/issues/346

## Tasks

codegen

- [x] https://github.com/awslabs/aws-sdk-swift/pull/607
- [x] https://github.com/awslabs/smithy-swift/pull/433

CRT integration

- [ ] https://github.com/awslabs/smithy-swift/pull/446
- [ ] https://github.com/awslabs/aws-crt-swift/pull/79
- [ ] https://github.com/awslabs/aws-sdk-swift/pull/634

- [x] I may be able to implement this feature request
