### ISSUE TITLE
[ECD 2/13] Flexible Checksums

### ISSUE THREAD

**Issue by ganeshnj** [awslabs/aws-sdk-swift#653]
### Describe the feature

seps/accepted/shared/flexible-checksums.md

### Use Case

Required for GA

### Proposed Solution

```[tasklist]
### Tasks
- [ ] https://github.com/awslabs/aws-crt-swift/issues/218
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1280
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1281
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1373
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jbelkins** [comment]
Please note this required behavior when implementing this SEP:
https://github.com/aws/aws-sdk-java-v2/issues/3569

**Comment by smivij** [comment]
Done is Kotlin and Rust, changing to priority 2

**Comment by dayaffe** [comment]
Will review related SEP during Friday review meeting and fill out relevant details in this Issue afterwards.

**Comment by sichanyoo** [comment]
We found that there exists dependency on chunk encoding SEP and CRT swift bindings before this can be implemented.

**Comment by dayaffe** [comment]
Should also address missing logs for ContentMD5Middleware.kt found here: https://github.com/smithy-lang/smithy-swift/blob/53fbde27f536f4287edfd4ff08bb5ebe8dc75169/Sources/ClientRuntime/Networking/Http/Middlewares/ContentMD5Middleware.swift#L35

**Comment by jbelkins** [comment]
`aws-crt-swift` 0.18.0 includes support for the four types of checksums needed:
https://github.com/awslabs/aws-crt-swift/releases/tag/0.18.0

**Comment by jbelkins** [comment]
Removing from Sprint 29 to focus on other features.  Will consider assigning this feature to Smithy team.

**Comment by jbelkins** [comment]
Shipped in AWS SDK for Swift 0.40.0
