### ISSUE TITLE
Modularizing Runtimes

### ISSUE THREAD

**Issue by ganeshnj** [awslabs/aws-sdk-swift#695]
### Describe the feature

Currently, there are two runtimes ClientRuntime and AWSClientRuntimes. This doesn't go with ref arch, the SDK's core layers must be modular that are reusable and forward compatible.

```[tasklist]
### Tasks
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1222
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1381
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1382
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1383
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1384
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1385
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1386
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1532
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1571
```

### Use Case

This will allow smithy and AWS customers to use the packages independently with higher predictability of the APIs. 

### Proposed Solution

Look at BLutAjCv8XUt quip. By using it as a reference
- [ ] Design the package structure including the Test packages
- [ ] Implement the solution

### Acknowledgements

- [ ] I may be able to implement this feature request
- [x] This feature might incur a breaking change
