### ISSUE TITLE
Event Streaming implementation

### ISSUE THREAD

**Issue by ganeshnj** [awslabs/aws-sdk-swift#870]
### Describe the feature

```[tasklist]
### Tasks
- [x] Refactor streaming support for request/responses 
 - [x] https://github.com/awslabs/smithy-swift/pull/530
 - [ ] https://github.com/awslabs/aws-sdk-swift/pull/889
 - [ ] https://github.com/awslabs/aws-crt-swift/pull/165
 - [ ] 
- [ ] Codegen support for shape serialization/deserialization to the vnd.amazon.event-stream content type
- [ ] Runtime support for framing of vnd.amazon.event-stream content type
- [ ] Integration tests for serialization and deserialization of all message types (except unbound document members)
- [ ] Lift all errors out of the event stream
- [ ] Response streams (e.g. s3 select object) work
- [ ] Track initial request signature in the execution context
- [ ] HTTP/2 full duplex stream support of underlying HTTP engine(s)
- [ ] Signing support for event stream request messages
- [ ]  feat: add support for unbound event stream payloads
- [ ] Provide new examples for streaming operations
- [ ] Add service specific tests (integration, e2e, or replay) for all streaming operations
```

### Use Case

#transcribe

### Proposed Solution

#event

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change
