### ISSUE TITLE
Determine how to handle initial messages in event streams

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#976]
### Describe the feature

Initial messages are defined in the Smithy spec here: https://smithy.io/2.0/spec/streaming.html#initial-messages

Right now, initial messages are streamed to the SDK as `.sdkUnknown` events.  This is kind of contradictory, since initial messages are a documented Smithy feature.

Determine how initial messages should be handled, if different from the _status quo_, and implement.

```[tasklist]
### Tasks
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1163
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1164
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1172
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1175
```

### Use Case

To correctly handle initial messages and make them easily available to stream consumers.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change
